version = 0.1
[default.deploy.parameters]
stack_name = "get-the-met-app"
resolve_s3 = true
s3_prefix = "get-the-met-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
